### ISSUE TITLE
Yum is locked by another process

### ISSUE THREAD

**Issue by nordri** [ome/ansible-role-fluentd#7]
Hi!
I've found this issue running the playbook and I wonder if you could add `lock_timeout: ` parameter to the task https://github.com/ome/ansible-role-fluentd/blob/master/tasks/main.yml#L11

Something like

```
- name: fluentd | install
  become: true
  yum:
    name: "{{ fluentd_name }}"
    state: present
    lock_timeout: TIME IN SECONDS could be a variable
  notify:
    - restart fluentd
```

lock_timeout was added in 2.8 of ansible.builtin. Perhaps you need to create two tasks for <= 2.8 and > 2.8

Thanks a lot
